### ISSUE TITLE
All terminal examples assume a Mac

### ISSUE THREAD

**Issue by sgolanka** [learn-co-curriculum/bash-tutorial#13]
I am using a Windows PC, and can follow the examples, but so far I have been asked to open a Terminal window a few times to try things out...but Mac's Terminal and the Windows Command Prompt use different languages.

For instance, the command "pwd" does not work in a Windows command prompt; neither does LS (dir works instead).

Perhaps it should be made more clear.  This line, for instance, doesn't work for someone using a Windows PC:

Open up command prompt or terminal. Type in: pwd and hit return.

**Comment by AnnJohn** [comment]
Hi @sgolanka thanks for raising this issue. We definitely know it's a problem, but won't be able to fix it in the immediate future. But for now, could you use the Ask a Question tool in Learn and someone from our support team will be able to help you with this. You should also be using Nitrous so if you're not, then someone will help you out with that as well. Thanks!
