### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by frahman5** [learn-co-curriculum/bash-tutorial#4]
In the bash tutorial section, I believe there's a typo in this paragraph:

*Single-character options can typically be combined with each other may also have suffixes. For example, in the ls command, h is a suffix on the l flag meaning "human readable formats." They can be combined with a meaning "all information including permissions". Try these three together:*

Should it instead be *Single-character options can typically be combined with each other. For example, in the ls command....*?

Cheers,
Faiyam

**Comment by AnnJohn** [comment]
@frahman5 Thanks for the suggestion. Fixed, and closing the issue
